import './form.scss';
import '../../blocks/field-heading';
import '../../blocks/field-input';
import '../../blocks/dropdown';
import '../../blocks/checkbox-buttons';
import '../../blocks/radio-buttons';
import '../../blocks/toggle';
import '../../blocks/like-button';
import '../../blocks/rating';